# Generated by Django 4.1.3 on 2022-11-18 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('typing_meter', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtext',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
